### ISSUE TITLE
Using hound on Heroku

### ISSUE THREAD

**Issue by garj** [HashNuke/hound#246]
I deployed a Phoenix app that is using Hound with chrome driver to Heroku. I've also added the following chrome and chrome driver buildpacks to my Heroku app

- https://github.com/heroku/heroku-buildpack-google-chrome
- https://github.com/heroku/heroku-buildpack-chromedriver

my config.exs is as following:

# Configure Hound
config :hound, driver: "chrome_driver"

These steps however does not seem to be sufficient to run Hound on Heroku as I got these errors

2019-09-22T09:44:17.698124+00:00 app[web.1]: 09:44:17.697 [error] GenServer Hound.SessionServer terminating
2019-09-22T09:44:17.698162+00:00 app[web.1]: ** (RuntimeError) could not create a new session: econnrefused, check webdriver is running
2019-09-22T09:44:17.698165+00:00 app[web.1]:     (hound) lib/hound/session_server.ex:101: Hound.SessionServer.create_session/2
2019-09-22T09:44:17.698167+00:00 app[web.1]:     (hound) lib/hound/session_server.ex:78: Hound.SessionServer.handle_call/3

Can I know if it is possible to run Hound on Heroku at all? Or am I missing some setup required to run it correctly. Please advice. Thanks.

**Comment by Anonyfox** [comment]
any update on this?

**Comment by mbenatti** [comment]
Yes, add
https://github.com/heroku/heroku-buildpack-chromedriver
and
https://github.com/heroku/heroku-buildpack-google-chrome

and start chrome driver "/app/.chromedriver/bin/chromedriver"
